variable "adminSrcAddr" {}
variable "resourceOwner" {}
variable "location" {}
variable "resource_group_name" {}
variable "mgmt_subnet_id" {}
variable "int_subnet_id" {}
variable "ubuntu-hostname" {}
variable "ubuntu-username" {}
variable "ubuntu-password" {}
variable "instance_size" {}